spring:
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:29092}
    admin:
      properties:
        request.timeout.ms: ${KAFKA_REQUEST_TIMEOUT:5000}
    consumer:
      properties:
        session:
          timeout:
            ms: 30000
        heartbeat:
          interval:
            ms: 10000
        max:
          poll:
            records: ${KAFKA_CONSUMER_MAX_POLL_RECORDS:50}
            interval:
              ms: ${KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS:300000}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  cloud:
    stream:
      binders:
        binderName:
          type: kafka
      kafka:
        binder:
          replicationFactor: ${KAFKA_REPLICATION_FACTOR:-1}
          minPartitionCount: ${MIN_PARTITION_COUNT:3}
          requiredAcks: ${REQUIRED_ACKS:all}
          producerProperties:
            enable.idempotence: ${KAFKA_PRODUCER_ENABLE_IDEMPOTENCE:true}

consumer:
  group: ${GRPOUP:moderate-service}

