spring:
  sleuth:
    enabled: ${TRACE_ENABLED:true}
    sampler:
      probability: 1.0  # Процент запросов для трассировки (1.0 = 100%)
  zipkin:
    base-url: ${TRACE_URL:http://localhost:9411}  # Адрес Zipkin-сервера (если используется)